### PR TITLE
Allow any 4.x version

### LINKED ISSUE #88: Align required providers with azurerm release patterns
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

With the way the azurerm provider is being versioned and released, it will be much easier to consume this module if the required version constraints are adjusted.  Currently if a consumer wants to use this module and their practice is to stay up on the latest version of azurerm for bug fixes, it requires this module to frequently release updates.  

Proposed constraint:  ~> 4.0, < 5.0.0

This should at least allow ease of consumption until the next major release.

### New or Affected Resource(s)/Data Source(s)

required_providers

### Potential Terraform Configuration

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by spowser**
## Description

Allow versions between 4.0.0 and 5.0.0

Fixes #88 
Closes #88 
-->

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [X] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [X] Update to documentation

# Checklist

- [X] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ ] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by luke-taylor** [comment]
Nice work, I think `~> 4.0` would work better (taking the latest v4 minor GEQ 0), since 3.116.0 won't be compatible with the current code.

**Comment by spowser** [comment]
Ack.  Yes, the floor should be 4.0.x.  Thanks for catching that!

**Comment by luke-taylor** [comment]
@spowser Hey, another security PR has been merged and it's now causing merge conflicts here, can you quickly do a rebase to resolve these merge conflicts?

Also, it may be worth removing the < 5.0.0 part since it's redundant if we're using ~> 4.0 since this necessarily means < 5.0.0

**Comment by spowser** [comment]
@luke-taylor Done and removed the 5.0.0.

**Review by luke-taylor — APPROVED** [review]

**Pull request merged**
